######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 19 21:48:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
